name: desnet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  crypto: ^3.0.3
  equatable: ^2.0.5
  ethereum: ^6.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_pdfview: ^1.3.2
  get_it: ^7.6.6
  path_provider: ^2.0.15
  pinenacl: ^0.5.1
  url_launcher: ^6.2.3
  walletconnect_flutter_v2: ^2.1.13
  web3dart: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/json/Storage.json
    - assets/image/pikachu.png