// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC02RvHocw_xAtiwCpCzUMRc-zV_TwEtXg',
    appId: '1:513210187862:web:cfa177b9ae31ab97757bf7',
    messagingSenderId: '513210187862',
    projectId: 'medicalchain-20556',
    authDomain: 'medicalchain-20556.firebaseapp.com',
    storageBucket: 'medicalchain-20556.appspot.com',
    measurementId: 'G-HEYXRBWVWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzd7lft7WDnie4Vbrng80WkfGEDq5ks6s',
    appId: '1:513210187862:android:41b43c40ac6ff513757bf7',
    messagingSenderId: '513210187862',
    projectId: 'medicalchain-20556',
    storageBucket: 'medicalchain-20556.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARQVltwtBvUKTMdQMG6HXq-YrsW6SBd8Q',
    appId: '1:513210187862:ios:f16f582465b9a855757bf7',
    messagingSenderId: '513210187862',
    projectId: 'medicalchain-20556',
    storageBucket: 'medicalchain-20556.appspot.com',
    iosBundleId: 'com.company.healthchain.healthchain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARQVltwtBvUKTMdQMG6HXq-YrsW6SBd8Q',
    appId: '1:513210187862:ios:349cdb956ba00cbf757bf7',
    messagingSenderId: '513210187862',
    projectId: 'medicalchain-20556',
    storageBucket: 'medicalchain-20556.appspot.com',
    iosBundleId: 'com.company.healthchain.healthchain.RunnerTests',
  );
}
